# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170514_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_number',
        ),
    ]
