# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='institution',
        ),
        migrations.AddField(
            model_name='user',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='_user_supervisors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
