# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170723_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='institution',
            new_name='institutions',
        ),
    ]
