# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_remove_institution_members'),
        ('users', '0007_auto_20170723_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='institutions',
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='institutions.Institution'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
