# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_institutionjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionjoinrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionjoinrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
