# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_institution_admins'),
        ('users', '0011_auto_20170815_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionjoinrequest',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='institutionjoinrequest',
            name='notes',
        ),
        migrations.AlterUniqueTogether(
            name='institutionjoinrequest',
            unique_together=set([('created_by', 'institution')]),
        ),
    ]
