# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170815_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionjoinrequest',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='institutionjoinrequest',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institutionjoinrequest',
            name='approved',
            field=models.NullBooleanField(),
        ),
    ]
