# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_accounttype_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='subjects',
        ),
    ]
