version: '2'
#
#volumes:
#  pgdata:
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:8000"
#    volumes:
#      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    image: gcr.io/riverlearn-202119/api
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    volumes:
      - .:/var/www/riverlearn-api

    ports:
      - "8001:8000"

    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_DB: api
      POSTGRES_PASS: api_pass
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"