# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
