# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20170831_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='public',
        ),
    ]
