# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20170407_2131'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='csv_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='uploads.File'),
        ),
    ]
