# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exampaper_csv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='exampaper',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='studentpaperperformance',
            name='institution',
        ),
    ]
