# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_auto_20170709_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False, help_text='Deletes should deactivate not do actual deletes')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(blank=True, related_name='exam_results', to='common.Comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student_paper_performances', models.ManyToManyField(related_name='exam_result', to='exams.StudentPaperPerformance')),
            ],
        ),
    ]
