# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaperperformance',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Grade'),
        ),
    ]
