# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_studentpaperperformance_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='student_paper_performances',
            field=models.ManyToManyField(blank=True, related_name='exam_result', to='exams.StudentPaperPerformance'),
        ),
    ]
