# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0018_auto_20170916_1754'),
        ('exams', '0006_auto_20170814_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='class_level',
        ),
        migrations.AddField(
            model_name='exam',
            name='class_levels',
            field=models.ManyToManyField(related_name='exams', to='divisions.ClassLevel'),
        ),
    ]
