# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0019_classroom'),
        ('exams', '0007_auto_20171009_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='divisions.ClassRoom'),
        ),
    ]
