# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20171015_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='description',
            new_name='notes',
        ),
    ]
