# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0019_classroom'),
        ('exams', '0012_auto_20171022_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='_classes',
            field=models.ManyToManyField(blank=True, related_name='papers', to='divisions.Class'),
        ),
    ]
