# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_exampaper__classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampaper',
            name='csv_file',
        ),
    ]
