# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_remove_exampaper_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=uploads.models.unique_file_location),
        ),
    ]
