# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-05 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20170903_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divisions', '0019_classroom'),
        ('exams', '0016_auto_20171101_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassExamPaperPerformance',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False, help_text='Deletes should deactivate not do actual deletes')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_performances', to='divisions.Class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_performance', to='exams.ExamPaper')),
                ('student_performances', models.ManyToManyField(blank=True, related_name='class_performance', to='exams.StudentPaperPerformance')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassExamResult',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False, help_text='Deletes should deactivate not do actual deletes')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(blank=True, related_name='exam_results', to='common.Comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exam_paper_performances', models.ManyToManyField(blank=True, related_name='exam_result', to='exams.ClassExamPaperPerformance')),
            ],
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='student_paper_performances',
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
