# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-05 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_auto_20171105_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classexampaperperformance',
            options={},
        ),
    ]
