# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0019_classroom'),
        ('exams', '0018_auto_20171105_2205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentpaperperformance',
            unique_together=set([('student', 'paper')]),
        ),
    ]
