# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_auto_20171106_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classexampaperperformance',
            name='_class',
        ),
        migrations.RemoveField(
            model_name='classexampaperperformance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='classexampaperperformance',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='classexampaperperformance',
            name='student_performances',
        ),
        migrations.RemoveField(
            model_name='classexamresult',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='classexamresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='classexamresult',
            name='exam_paper_performances',
        ),
        migrations.AlterUniqueTogether(
            name='studentpaperperformance',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='studentpaperperformance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentpaperperformance',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentpaperperformance',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='studentpaperperformance',
            name='student',
        ),
        migrations.DeleteModel(
            name='ClassExamPaperPerformance',
        ),
        migrations.DeleteModel(
            name='ClassExamResult',
        ),
        migrations.DeleteModel(
            name='StudentPaperPerformance',
        ),
    ]
