# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20170903_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divisions', '0019_classroom'),
        ('exams', '0022_auto_20171106_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPaperPerformance',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False, help_text='Deletes should deactivate not do actual deletes')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('class_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_performances', to='exams.ClassExamResult')),
                ('comments', models.ManyToManyField(blank=True, related_name='class_paper_performances', to='common.Comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_performance', to='exams.ExamPaper')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False, help_text='Deletes should deactivate not do actual deletes')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('mark', models.FloatField(blank=True, default=0.0)),
                ('class_performance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='exams.ClassPaperPerformance')),
                ('comments', models.ManyToManyField(blank=True, related_name='student_paper_performances', to='common.Comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_performances', to='divisions.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentperformance',
            unique_together=set([('student', 'class_performance')]),
        ),
    ]
