# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_auto_20171106_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='divisions.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='classexamresult',
            unique_together=set([]),
        ),
    ]
