# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_auto_20171213_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classexamresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_result', to='exams.Exam'),
        ),
    ]
