# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0019_classroom'),
        ('exams', '0025_auto_20171214_1602'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classexamresult',
            unique_together=set([('exam', '_class')]),
        ),
    ]
