# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-03 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_auto_20171224_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
