# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0029_studentperformance_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentperformance',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='studentperformance',
            unique_together=set([]),
        ),
    ]
