# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0008_auto_20170814_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='color',
        ),
    ]
