# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20170831_1936'),
        ('divisions', '0009_remove_stream_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Color'),
        ),
    ]
