# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0011_institutionsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='divisions.InstitutionSubject'),
        ),
    ]
