# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0012_auto_20170903_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionsubject',
            old_name='subject',
            new_name='field',
        ),
        migrations.AddField(
            model_name='institutionsubject',
            name='name',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
