# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0013_auto_20170903_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionsubject',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
