# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divisions', '0014_auto_20170903_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institutionsubject',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_subjects', to='common.Subject'),
        ),
    ]
