# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0017_auto_20170911_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user']},
        ),
    ]
