# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0003_auto_20170407_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False, help_text='Deletes should deactivate not do actual deletes')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Deletes should deactivate not do actual deletes'),
        ),
        migrations.AddField(
            model_name='institution',
            name='members',
            field=models.ManyToManyField(related_name='institution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionitem',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='institutions.Institution'),
        ),
    ]
