# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_auto_20170709_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='institutionitem',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='active',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='institution',
            name='members',
            field=models.ManyToManyField(related_name='institutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='InstitutionItem',
        ),
    ]
