# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_auto_20170720_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='members',
        ),
    ]
