# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_remove_institution_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='motto',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
