# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0009_auto_20170813_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='admins',
            field=models.ManyToManyField(related_name='admin_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
