# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    def gen_unique_domain(apps, schema_editor):
        MyModel = apps.get_model('institutions', 'Institution')
        for row in MyModel.objects.all():
            row.domain = row.name
            row.save()

    dependencies = [
        ('institutions', '0011_institution_domain'),
    ]

    operations = [
        migrations.RunPython(gen_unique_domain, reverse_code=migrations.RunPython.noop),
    ]
