# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_auto_20170819_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('divisions_name', models.CharField(blank=True, max_length=255, null=True)),
                ('levels', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='institution',
            name='domain',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
