# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0014_auto_20170819_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionType'),
        ),
    ]
