# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20170407_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='image',
            name='institution',
        ),
    ]
